version: 2.1

orbs:
	aws-parameter-store: circleci/aws-parameter-store@dev:alpha
	orb-tools: circleci/orb-tools@8.27.4

jobs:
	command-load-test:
		executor: orb-tools/node-cci
		steps:
			- aws-parameter-store/load:
					filter: ""
			- run:
					name: Validate Env Vars
					command: cat /tmp/parameterstore/PARAMETERSTORESOURCEFILE

workflows:
	# this `lint-pack_validate_publish-dev` workflow will run on any commit
	lint-pack_validate_publish-dev:
		jobs:
			# lint your destructured orb YAML files
			- orb-tools/lint

			# pack your orb YAML files to a single orb.yml
			# validate the orb.yml file to ensure it is well-formed
			- orb-tools/pack:
					requires:
						- orb-tools/lint

			# release dev version of orb, for testing & possible publishing
			# requires a CircleCI API token to be stored as CIRCLE_TOKEN (default)
			# https://circleci.com/docs/2.0/managing-api-tokens
			# store CIRCLE_TOKEN as a project env var or Contexts resource
			# if using Contexts, add your context below
			- orb-tools/publish-dev:
					orb-name: "circleci/aws-parameter-store"
					requires:
						- orb-tools/pack

			# trigger an integration workflow to test the dev version of your orb
			# an SSH key must be stored in your orb's repository and in CircleCI
			# (add the public key as a read/write key on GitHub; add the private
			# key in CircleCI via SSH Permissions, with github.com as Hostname)
			- orb-tools/trigger-integration-workflow:
					name: trigger-integration-dev
					ssh-fingerprints: "bd:0c:45:b7:61:47:f1:34:42:9f:c9:48:5e:11:d0:20"
					requires:
						- orb-tools/publish-dev
					filters:
						branches:
							ignore: master

			# by default, the 1st job (above) will trigger only integration tests;
			# the 2nd job (below) may also publish a production orb version
			- orb-tools/trigger-integration-workflow:
					name: trigger-integration-master
					ssh-fingerprints: "bd:0c:45:b7:61:47:f1:34:42:9f:c9:48:5e:11:d0:20"
					tag: master
					requires:
						- orb-tools/publish-dev
					filters:
						branches:
							only: master

# yaml anchor filters
integration-dev_filters: &integration-dev_filters
  branches:
    ignore: /.*/
  tags:
    only: /integration-.*/

integration-master_filters: &integration-master_filters
  branches:
    ignore: /.*/
  tags:
    only: /master-.*/

prod-deploy_requires: &prod-deploy_requires
  [
    command-load-test-master
  ]

	# this `integration-tests_prod-release` workflow will ignore commits
	# it is only triggered by git tags, which are created in the job above
	integration-tests_prod-release:
		jobs:
			- command-load-test:
					name: command-load-test-dev
					filters: *integration-dev_filters

			- command-load-test:
					name: command-load-test-master
	        filters: *integration-master_filters

			# patch, minor, or major publishing
			- orb-tools/dev-promote-prod:
					name: dev-promote-patch
					context: orb-publishing
					orb-name: circleci/orb-tools
					ssh-fingerprints: 2a:2b:49:ea:64:7d:39:4a:58:17:18:17:b2:5c:f6:a8
					cleanup-tags: true
					requires: *prod-deploy_requires
					filters:
						branches:
							ignore: /.*/
						tags:
							only: /master-patch.*/

			- orb-tools/dev-promote-prod:
					name: dev-promote-minor
					context: orb-publishing
					release: minor
					orb-name: circleci/orb-tools
					ssh-fingerprints: 2a:2b:49:ea:64:7d:39:4a:58:17:18:17:b2:5c:f6:a8
					cleanup-tags: true
					requires: *prod-deploy_requires
					filters:
						branches:
							ignore: /.*/
						tags:
							only: /master-minor.*/

			- orb-tools/dev-promote-prod:
					name: dev-promote-major
					context: orb-publishing
					release: major
					ssh-fingerprints: 2a:2b:49:ea:64:7d:39:4a:58:17:18:17:b2:5c:f6:a8
					cleanup-tags: true
					orb-name: circleci/orb-tools
					ssh-fingerprints: 2a:2b:49:ea:64:7d:39:4a:58:17:18:17:b2:5c:f6:a8
					cleanup-tags: true
					requires: *prod-deploy_requires
					filters:
						branches:
							ignore: /.*/
						tags:
							only: /master-major.*/
